from .doc_parser import read_google_doc
from .canvas_api import (
    create_course,
    import_base_course_files,
    create_module,
    list_modules,
    publish_module,
    create_assignment,
    list_assignments,
    list_assignment_groups,
    enable_assignment_group_weights,
    create_or_update_assignment_group,
    delete_assignment,
    create_or_update_assignment_rubric,
    add_item_to_module,
    update_course_home_page,
    update_course_syllabus,
    create_page,
    create_discussion_topic,
    set_module_position,
    list_course_files,
)

canvas_tools = [
    create_course,
    import_base_course_files,
    create_module,
    list_modules,
    publish_module,
    create_assignment,
    list_assignments,
    list_assignment_groups,
    enable_assignment_group_weights,
    create_or_update_assignment_group,
    delete_assignment,
    create_or_update_assignment_rubric,
    add_item_to_module,
    update_course_home_page,
    update_course_syllabus,
    create_page,
    create_discussion_topic,
    set_module_position,
    list_course_files,
]
